[package]
name = "rama-ws"
description = "WebSocket (WS) support for rama (RFC 6455)"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = ["io", "async", "websocket", "http", "rama"]
categories = ["asynchronous", "network-programming", "web-programming"]
authors = { workspace = true }
rust-version = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
rama-core = { workspace = true }
rama-http = { workspace = true }
rama-utils = { workspace = true }
tokio = { workspace = true, features = ["time", "macros"] }

[dev-dependencies]

[lints]
workspace = true
